name: Update milestone after release
on:
  push:
    branches:
      - trunk

jobs:
  RandomTest:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/tarunvijwani/woocommerce-blocks/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Testing"
      - uses: octokit/request-action@v2.x
        id: get_milestone
        with:
          route: GET /repos/tarunvijwani/woocommerce-blocks/milestones/
          owner: octokit
          repo: request-action
          state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Testing"
      - run: "echo latest release: ${{ fromJSON(steps.get_milestone.outputs.data) }}"
