name: Manual milestone update
on: workflow_dispatch

jobs:
  RandomTest:
    runs-on: ubuntu-latest
    steps:
      - name: Manually update milestone
        uses: tarunvijwani/automations@trunk
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            automations: update-milestone
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Tag name: ${{ steps.previoustag.outputs.tag }}"
