name: Manual milestone update
on: workflow_dispatch

jobs:
  RandomTest:
    runs-on: ubuntu-latest
    steps:
      - name: Manually update milestone
              uses: tarunvijwani/automations@add/update-milestone-after-release
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  automations: release
      - run: "echo Testing"
