name: Manual milestone update
on: workflow_dispatch

jobs:
  RandomTest:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3
        with:
            fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - run: "echo Tag name: ${{ steps.previoustag.outputs.tag }}"
      - name: Manually update milestone
        uses: tarunvijwani/automations@trunk
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            automations: update-milestone
            target_milestone: ${{ steps.previoustag.outputs.tag }}
