name: Update milestone after release
on:
  push:
    branches:
      - trunk

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/tarunvijwani/woocommerce-blocks/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Testing"
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data[tag_name] }}"
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
      - run: "echo testing ended"
