name: Deploy to WordPress.org
on:
    release:
        types: [published]
jobs:
    tag:
        name: New Release
        runs-on: ubuntu-latest
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: 'Get Previous tag'
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
            - run: "echo Milestone name: ${{ steps.previoustag.outputs.tag }}"
            - name: Manually update milestone
              uses: tarunvijwani/automations@trunk
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                automations: update-milestone
                target_milestone: ${{ steps.previoustag.outputs.tag }}
